### ISSUE TITLE
试了下虎牙，输入网址后，显示“主播 当前不在播”

### ISSUE THREAD

**Issue by fanglangxinghai** [jlvihv/liveship#1]
下载的是v0.1.10的liveship_0.1.10_x64-setup.exe

**Comment by jlvihv** [comment]
感谢报告，这是一个bug，现在已修复，请下载  [v0.1.11](https://github.com/jlvihv/liveship/releases/tag/liveship-v0.1.11) 版本试试。
虎牙检测比较严格，获取虎牙的主播信息的时候，不能开代理，不然可能获取不到，多试几次可能解决。
不过获取不到也没关系，可以加入录制计划，程序会自动重试。

**Comment by fanglangxinghai** [comment]
> 感谢报告，这是一个bug，现在已修复，请下载 [v0.1.11](https://github.com/jlvihv/liveship/releases/tag/liveship-v0.1.11) 版本试试。 虎牙检测比较严格，获取虎牙的主播信息的时候，不能开代理，不然可能获取不到，多试几次可能解决。 不过获取不到也没关系，可以加入录制计划，程序会自动重试。

嗯，下了新的这个版本，把代理关了，还是获取不到主播信息。加入录制计划，却是过了一会开始自动下载视频了。

不过你这个似乎是不能录制弹幕，那感觉就少了很多味。

**Comment by jlvihv** [comment]
不打算添加录制弹幕的功能哦
